name: GitHub Pages

on:
  push

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: lcov
        run: sudo apt-get update && sudo apt-get install -y lcov

      - name: tools
        run: make tools

      - name: coverage
        run: |
          percent=$(make coverage | grep lines | sed -r 's/[^0-9]*(.*\.[0-9]*)%.*/\1/' | sed -e 's/%/%25/')
          int=${percent%.*}
          if [ $int -gt 90 ]; then
            curl -o site/coverage.svg https://img.shields.io/badge/coverage-${percent}%25-green
          elif [ $int -gt 75 ]; then
            curl -o site/coverage.svg https://img.shields.io/badge/coverage-${percent}%25-yellow
          else
            curl -o site/coverage.svg https://img.shields.io/badge/coverage-${percent}%25-red
          fi

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
